class Config:
    home_path_dir = '/Users/yafei/data'
    son_source_dir = home_path_dir + '/original/son'
    others_source_dir = home_path_dir + '/original/others'
    son_train_dir = home_path_dir + '/train'
    son_val_dir = home_path_dir + '/val'
    others_train_dir = home_path_dir + '/train/others'
    others_val_dir = home_path_dir + '/val/others'
    model_save_path = home_path_dir + '/models/son_recognition_vit.pth'
    test_image_path = home_path_dir + '/test.png'
